name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest-9 --activate
          pnpm install
          pnpm build

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker.io
        uses: docker/build-push-action@v6.1.0
        with:
          push: true
