name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest-9 --activate
          pnpm install
          pnpm build


      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
